apiVersion: batch/v1
kind: Job
metadata:
  name: {{ (cat .Release.Name "-cleanup-jobs-" ( .Values.service.name | lower | replace " " "-") "-" ( randAlphaNum 5 | lower )) | nospace | trunc 63 }} 
  namespace: {{ .Release.Namespace }}
  labels:
    bluemixService: {{ .Values.service.name | lower | replace " " "-" }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "999"
spec:
  template:
    metadata:
      name: {{.Release.Name}}-cleanup-jobs-{{ .Values.service.name | lower | replace " " "-" }}
      labels:
        bluemixService: {{ .Values.service.name | lower | replace " " "-" }}
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cleanup-jobs
        image: ibmcase/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c" ]
        args: 
        - >
            set -x;
            echo kubectl delete jobs -l bluemixService={{ .Values.service.name | lower | replace " " "-" }},chart={{.Chart.Name}}-{{.Chart.Version}},release={{.Release.Name}} --cascade;
            kubectl delete jobs -l bluemixService={{ .Values.service.name | lower | replace " " "-" }},chart={{.Chart.Name}}-{{.Chart.Version}},release={{.Release.Name}} --cascade;

