{{ if not .Values.hs256key.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "customer.hs256SecretName" . }}
  labels:
    {{- include "customer.labels" . | indent 4 }}
data:
  key: {{ (.Values.hs256key.secret | default (randAlphaNum 256)) | b64enc }}
type: Opaque
{{ end }}