replicaCount: 1

image:
  repository: ibmcase/bluecompute-customer
  tag: 0.5.0
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 8082
  internalPort: 8082
  nodePort: 31382

ingress:
  enabled: false
  hostname: customer.bluecompute.com
  path: /micro/customer
  ibmCloud:
    redirectToHTTPS: false

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

hs256key:
  # If there is an existing secret with the key, provide it here
  secretName:
  secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

global:
  hs256key:
    secretName:

testUser:
  createUser: true
  username: user
  password: passw0rd

bash:
  image:
    repository: ibmcase/bluecompute-bash-curl-ssl
    tag: latest
    pullPolicy: IfNotPresent

couchdb:
  host: customer-couchdb-svc-couchdb
  protocol: http
  port: 5985
  existingSecret:
  adminUsername: user
  adminPassword: passw0rd

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi

labels:
  app: customer
  version: v1
  tier: backend