replicaCount: 1

image:
  repository: ibmcase/bluecompute-customer
  pullPolicy: Always
  tag: 0.5.0

service:
  name: customer
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

ingress:
  enabled: false
  hostname: customer.bluecompute.com
  path: /micro/customer

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

hs256key:
  # If there is an existing secret with the key, provide it here
  secretName:
  secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

bash:
  image:
    repository: ibmcase/bluecompute-bash-curl-ssl
    tag: latest
    pullPolicy: IfNotPresent

# Included Community Couchdb Chart.
# - Even if disabled, these fields are used to provide information
#   for external CouchDB deployments.
customercouchdb:
  enabled: true
  image: 
    repository: "couchdb"
    tag: "2.1.1"
    pullPolicy: IfNotPresent
  # If chart is not enabled, this field can be used as external mysql host
  fullnameOverride: bluecompute-customer
  protocol: http
  createAdminSecret: true
  adminUsername: user
  adminPassword: passw0rd
  service:
    externalPort: 5984
  clusterSize: 1
  persistentVolume:
    enabled: false
  helperImage:
    repository: kocolosk/couchdb-statefulset-assembler
    tag: 1.1.0
    pullPolicy: IfNotPresent

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi